# Dedplay Stüdyo 0.5.23 yaması: kitap raporu (ölçüm). Kod klasöründe çalıştırılır: python3 rapor_0523_yama.py
# Yeni dosyalar: kutuphane/rapor.py, tests/test_rapor.py. Değişen: kutuphane/kaynak.py, depo.py, main.py (yalnız kayıt
# çağrıları; metin işleme değişmez). Tekrar çalıştırılabilir.
import base64, hashlib, pathlib, sys
if not pathlib.Path("kutuphane/kaynak.py").exists():
    sys.exit("HATA: kod klasöründe değilsin (cd /DATA/AppData/dedplay-studyo/kod/studyo)")
if 'SURUM = "0.5.22"' not in pathlib.Path("kutuphane/main.py").read_text(encoding="utf-8") and \
        'SURUM = "0.5.23"' not in pathlib.Path("kutuphane/main.py").read_text(encoding="utf-8"):
    sys.exit("HATA: önce 0.5.22 uygulanmış olmalı")
YENI = {
    "kutuphane/rapor.py": """
IiIiMC41LjIzOiBLaXRhcCByYXBvcnUgKMO2bMOnw7xtKS4gS2l0YXAgacWfbGVuaXJrZW4gbWV0aW5kZSB5YXDEsWxhbiBoZXIg
ZGXEn2nFn2lrbGlrIChrZWxpbWUgb25hcsSxbcSxLCBiaXJsZcWfdGlybWUpLCBzaWxpbmVuCmhlciDFn2V5ICjDvHN0IGJpbGdp
IHNhdMSxcsSxLCDDp8O2cCBwYXJhZ3JhZiwgYXTEsWxhbiBzYXlmYSwgYmHEn2xhbmFtYXlhbiBkaXBub3QpIGtheWRlZGlsaXI7
IGnFnyBiaXRpbmNlIHlhcMSxIGRlbmV0aW1pCihudW1hcmFsxLEgYmHFn2zEsWtsYXJkYSBla3Npaywgc2F5ZmEgbnVtYXJhc8Sx
bmRhIGF0bGFtYSwgZGlwbm90IGnFn2FyZXRpL21ldG5pIGXFn2xlxZ9tZXNpKSwgxZ/DvHBoZWxpIGtlbGltZWxlciB2ZSDFn8O8
cGhlbGkKcGFyYWdyYWZsYXJsYSBiaXJsaWt0ZSBraXRhYsSxbiBrbGFzw7Zyw7xuZSByYXBvci5qc29uICsgcmFwb3IudHh0IG9s
YXJhayB5YXrEsWzEsXIuIE1ldG5pIERFxJ7EsMWeVMSwUk1FWiwgeWFsbsSxeiBrYXlkZWRlci4KCktvbXV0bGFyIChrb250ZXlu
ZXJkZSk6CiAgcHl0aG9uIC1tIGt1dHVwaGFuZS5yYXBvciB0b3BsdSAgICAgICAgYsO8dMO8biBraXRhcGxhcsSxbiByYXBvcmxh
csSxbsSxbiDDtnpldGkgKHRlayBtZXRpbikKICBweXRob24gLW0ga3V0dXBoYW5lLnJhcG9yIGt1cnUgW2tpZF0gICBrdXJ1IGRl
bmVtZToga2l0YXBsYXLEsSB5ZW5pIGtvZGxhIHllbmlkZW4gacWfbGVyIChPQ1Igw7ZuYmVsbGVrdGVuKSwgaGnDp2JpciDFn2V5
aQogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIGtheWRldG1lejsgcmFwb3J1IHZlIMWfaW1kaWtpIGtp
dGFwbGEgZmFya8SxIC9kYXRhL2t1cnVfZGVuZW1lIGFsdMSxbmEgeWF6YXIKIiIiCmltcG9ydCBjb2xsZWN0aW9ucywgZGlmZmxp
YiwganNvbiwgb3MsIHJlLCBzeXMsIHRocmVhZGluZywgdGltZQoKX3llcmVsID0gdGhyZWFkaW5nLmxvY2FsKCkKX1NBWUZBID0g
cmUuY29tcGlsZSgiXHVlMDAyKFteXHVlMDAzXXsxLDIwfSlcdWUwMDMiKQpfTk9UID0gcmUuY29tcGlsZShyIlx7XHtuXGR7NCx9
XH1cfSIpCl9BUkFQID0gcmUuY29tcGlsZShyIltcdTA2MDAtXHUwNkZGXHUwNzUwLVx1MDc3Rlx1RkI1MC1cdUZERkZcdUZFNzAt
XHVGRUZGXSIpCl9LRUxJTUUgPSByZS5jb21waWxlKHIiW15cV1xkX117Mix9IikKU1VSVU0gPSAxCgoKIyA9PT09PT09PT09PT09
PT09PT09PT09PSBrYXnEsXQgKGnFnyBzw7xyZXJrZW4pID09PT09PT09PT09PT09PT09PT09PT09CmRlZiBiYXNsYSgpOgogICAg
X3llcmVsLmsgPSB7ImRlZ2lzaWtsaWsiOiB7fSwgIm5va3RhbGFtYSI6IDAsICJzaWxpbmVuIjogY29sbGVjdGlvbnMuZGVmYXVs
dGRpY3QoY29sbGVjdGlvbnMuQ291bnRlciksCiAgICAgICAgICAgICAgICAic2lsaW5lbl9vcm5layI6IHt9LCAic2F5ZmEiOiBO
b25lfQogICAgX3llcmVsLnNvbiA9IE5vbmUKCgpkZWYgX2soKToKICAgIHJldHVybiBnZXRhdHRyKF95ZXJlbCwgImsiLCBOb25l
KQoKCmRlZiBfdGVtaXoodCk6CiAgICByZXR1cm4gcmUuc3ViKHIiXHMrIiwgIiAiLCBfTk9ULnN1YigiIiwgX1NBWUZBLnN1Yigi
ICIsIHQgb3IgIiIpKSkuc3RyaXAoKQoKCmRlZiBmYXJrKG9uY2UsIHNvbnJhLCB5ZXI9Im1ldGluIik6CiAgICAiIiJCaXIgcGFy
YWdyYWbEsW4gw7ZuY2VraSB2ZSBzb25yYWtpIGjDomxpOiBrZWxpbWUgZMO8emV5aW5kZWtpIGRlxJ9pxZ9pa2xpa2xlciBrYXlk
ZWRpbGlyLiIiIgogICAgayA9IF9rKCkKICAgIGlmIGsgaXMgTm9uZSBvciBvbmNlID09IHNvbnJhOgogICAgICAgIHJldHVybgog
ICAgYSwgYiA9IG9uY2Uuc3BsaXQoKSwgc29ucmEuc3BsaXQoKQogICAgc2F5ZmFsYXIgPSBbXSAgIyBoZXIga2VsaW1leWUga2Fk
YXIgZ8O2csO8bGVuIHNvbiBzYXlmYQogICAgc29uID0ga1sic2F5ZmEiXQogICAgZm9yIHQgaW4gYToKICAgICAgICBmb3IgbSBp
biBfU0FZRkEuZmluZGl0ZXIodCk6CiAgICAgICAgICAgIHNvbiA9IG0uZ3JvdXAoMSkKICAgICAgICBzYXlmYWxhci5hcHBlbmQo
c29uKQogICAgZm9yIHQgaW4gYjoKICAgICAgICBmb3IgbSBpbiBfU0FZRkEuZmluZGl0ZXIodCk6CiAgICAgICAgICAgIGtbInNh
eWZhIl0gPSBtLmdyb3VwKDEpCiAgICBmb3Igb3AsIGkxLCBpMiwgajEsIGoyIGluIGRpZmZsaWIuU2VxdWVuY2VNYXRjaGVyKE5v
bmUsIGEsIGIsIGF1dG9qdW5rPUZhbHNlKS5nZXRfb3Bjb2RlcygpOgogICAgICAgIGlmIG9wID09ICJlcXVhbCI6CiAgICAgICAg
ICAgIGNvbnRpbnVlCiAgICAgICAgeCwgeSA9IF90ZW1peigiICIuam9pbihhW2kxOmkyXSkpLCBfdGVtaXooIiAiLmpvaW4oYltq
MTpqMl0pKQogICAgICAgIGlmIHggPT0geToKICAgICAgICAgICAgY29udGludWUKICAgICAgICBpZiByZS5zdWIociJbXFdfXSIs
ICIiLCB4KSA9PSByZS5zdWIociJbXFdfXSIsICIiLCB5KTogICMgeWFsbsSxeiBib8WfbHVrL25va3RhbGFtYQogICAgICAgICAg
ICBrWyJub2t0YWxhbWEiXSArPSAxCiAgICAgICAgICAgIGNvbnRpbnVlCiAgICAgICAgaWYgbGVuKHgpID4gNjAgb3IgbGVuKHkp
ID4gNjA6CiAgICAgICAgICAgIHgsIHkgPSB4Wzo2MF0gKyAi4oCmIiwgeVs6NjBdICsgIuKApiIKICAgICAgICBhbmFodGFyID0g
KHgsIHksIHllcikKICAgICAgICBkID0ga1siZGVnaXNpa2xpayJdLnNldGRlZmF1bHQoYW5haHRhciwgeyJhZGV0IjogMCwgInNh
eWZhIjogc2F5ZmFsYXJbaTFdIGlmIGkxIDwgbGVuKHNheWZhbGFyKSBlbHNlIHNvbiwKICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICJiYWdsYW0iOiBfdGVtaXooIiAiLmpvaW4oYlttYXgoMCwgajEgLSA1KTpqMiArIDVd
KSlbOjE2MF19KQogICAgICAgIGRbImFkZXQiXSArPSAxCgoKZGVmIHNpbGluZGkodHVyLCBtZXRpbik6CiAgICAiIiJNZXRpbmRl
biBhdMSxbGFuIGJpciDFn2V5ICh0w7xyOiAnw7xzdC9hbHQgYmlsZ2kgc2F0xLFyxLEnLCAnw6fDtnAgcGFyYWdyYWYnLCAnYXTE
sWxhbiBzYXlmYScsICdiYcSfbGFuYW1heWFuIGRpcG5vdCcgLi4uKS4iIiIKICAgIGsgPSBfaygpCiAgICBpZiBrIGlzIE5vbmU6
CiAgICAgICAgcmV0dXJuCiAgICB0ID0gX3RlbWl6KG1ldGluKVs6MTYwXQogICAgaWYgdDoKICAgICAgICBrWyJzaWxpbmVuIl1b
dHVyXVt0XSArPSAxCgoKZGVmIGJpdGlyKGtpdCwgYmlsZ2k9Tm9uZSwgdXphbnRpPSIiKToKICAgICIiIsSwxZ8gYml0dGk6IHJh
cG9ydSBvbHXFn3R1cnVyIChpxZ8gcGFyw6dhY8SxxJ/EsW5hIMO2emVsOyBkZXBvIGBhbGAgaWxlIGFsxLFyKS4iIiIKICAgIGsg
PSBfaygpCiAgICBfeWVyZWwuayA9IE5vbmUKICAgIHRyeToKICAgICAgICBfeWVyZWwuc29uID0gb2x1c3R1cihraXQsIGsgb3Ig
e30sIGJpbGdpIG9yIHt9LCB1emFudGkpCiAgICBleGNlcHQgRXhjZXB0aW9uIGFzIGU6ICAjIHJhcG9yIGtpdGFixLFuIGnFn2xl
bm1lc2luaSBhc2xhIGR1cmR1cm1hegogICAgICAgIF95ZXJlbC5zb24gPSB7ImhhdGEiOiBmInt0eXBlKGUpLl9fbmFtZV9ffTog
e2V9In0KICAgIHJldHVybiBfeWVyZWwuc29uCgoKZGVmIGFsKCk6CiAgICByID0gZ2V0YXR0cihfeWVyZWwsICJzb24iLCBOb25l
KQogICAgX3llcmVsLnNvbiA9IE5vbmUKICAgIHJldHVybiByCgoKIyA9PT09PT09PT09PT09PT09PT09PT09PSByYXBvciA9PT09
PT09PT09PT09PT09PT09PT09PQpkZWYgX2R6KCk6CiAgICBmcm9tIGFwcCBpbXBvcnQgZHV6ZWx0IGFzIERaCiAgICByZXR1cm4g
RFoKCgpfZ2VjZXJsaV9vbmJlbGxlayA9IHt9CgoKZGVmIF9nZWNlcmxpKHcpOgogICAgaWYgdyBub3QgaW4gX2dlY2VybGlfb25i
ZWxsZWs6CiAgICAgICAgRFogPSBfZHooKQogICAgICAgIHRyeToKICAgICAgICAgICAgX2dlY2VybGlfb25iZWxsZWtbd10gPSBi
b29sKERaLmdlY2VybGlfbWkodykgb3IgRFouX2tlbGltZV9taSh3KSkKICAgICAgICBleGNlcHQgRXhjZXB0aW9uOgogICAgICAg
ICAgICBfZ2VjZXJsaV9vbmJlbGxla1t3XSA9IFRydWUKICAgIHJldHVybiBfZ2VjZXJsaV9vbmJlbGxla1t3XQoKCmRlZiBfa3Vj
dWsodyk6CiAgICByZXR1cm4gdy5yZXBsYWNlKCJJIiwgIsSxIikucmVwbGFjZSgixLAiLCAiaSIpLmxvd2VyKCkKCgpkZWYgX3Nh
eWkoZSk6CiAgICByZXR1cm4gaW50KGUpIGlmIHJlLmZ1bGxtYXRjaChyIlxkezEsNH0iLCBlIG9yICIiKSBlbHNlIE5vbmUKCgpk
ZWYgb2x1c3R1cihraXQsIGssIGJpbGdpLCB1emFudGkpOgogICAga3UgPSBraXQuZ2V0KCJrdW55ZSIsIHt9KQogICAgYmxva2xh
ciA9IGtpdC5nZXQoImJsb2tsYXIiLCBbXSkKICAgIGRpbCA9IGt1LmdldCgiYXNpbF9kaWwiLCAidHIiKQogICAgciA9IHsic3Vy
dW0iOiBTVVJVTSwgInRhcmloIjogaW50KHRpbWUudGltZSgpKSwKICAgICAgICAgImtpdGFwIjogeyJhZCI6IChrdS5nZXQoImJh
c2xpayIpIG9yIHt9KS5nZXQoInRyIikgb3IgKGt1LmdldCgiYmFzbGlrIikgb3Ige30pLmdldChkaWwsICIiKSwKICAgICAgICAg
ICAgICAgICAgICJ5YXphciI6IChrdS5nZXQoInlhemFyIikgb3Ige30pLmdldCgidHIiLCAiIiksICJrYXluYWsiOiAoa3UuZ2V0
KCJrYXluYWsiKSBvciB7fSkuZ2V0KCJhZCIsICIiKSwKICAgICAgICAgICAgICAgICAgICJ0dXIiOiB1emFudGkubHN0cmlwKCIu
Iikgb3IgIm1ldGluIiwgImRpbCI6IGRpbH0sCiAgICAgICAgICJjaWthcm1hIjogeyJzYXlmYSI6IGJpbGdpLmdldCgic2F5ZmEi
KSwgIm9jcl9zYXlmYSI6IGJpbGdpLmdldCgib2NyIiksICJvY3JfbW90b3J1IjogYmlsZ2kuZ2V0KCJvY3JfbW90b3J1IiksCiAg
ICAgICAgICAgICAgICAgICAgICJib3p1a19rYXRtYW4iOiBiaWxnaS5nZXQoImJvenVrX2thdG1hbiIpLCAib25hcmltIjogKGt1
LmdldCgiY2lrYXJtYSIpIG9yIHt9KS5nZXQoIm9uYXJpbSIpfX0KICAgIG1ldGluID0gbGFtYmRhIGI6IChiLmdldCgibWV0aW4i
KSBvciB7fSkuZ2V0KGRpbCkgb3IgKGIuZ2V0KCJtZXRpbiIpIG9yIHt9KS5nZXQoInRyIikgb3IgIiIKICAgIHBhcmFncmFmbGFy
ID0gW2IgZm9yIGIgaW4gYmxva2xhciBpZiBiLmdldCgidHVyIikgPT0gInAiXQogICAgYmFzbGlrbGFyID0gW2IgZm9yIGIgaW4g
Ymxva2xhciBpZiBiLmdldCgidHVyIikgPT0gImJhc2xpayJdCiAgICBrZWxpbWUgPSBzdW0obGVuKF90ZW1peihtZXRpbihiKSku
c3BsaXQoKSkgZm9yIGIgaW4gYmxva2xhcikKICAgIHJbIm96ZXQiXSA9IHsicGFyYWdyYWYiOiBsZW4ocGFyYWdyYWZsYXIpLCAi
YmFzbGlrIjogbGVuKGJhc2xpa2xhciksICJrZWxpbWUiOiBrZWxpbWUsCiAgICAgICAgICAgICAgICAgImRpcG5vdCI6IGxlbihr
aXQuZ2V0KCJkaXBub3RsYXIiKSBvciB7fSksCiAgICAgICAgICAgICAgICAgInNldml5ZSI6IGRpY3QoY29sbGVjdGlvbnMuQ291
bnRlcihzdHIoYi5nZXQoInNldml5ZSIsIDEpKSBmb3IgYiBpbiBiYXNsaWtsYXIpKX0KICAgICMgLS0tIHlhcMSxIGRlbmV0aW1p
IC0tLQogICAgeWFwaSA9IHsiYmFzbGlrbGFyIjogW1tiLmdldCgic2V2aXllIiwgMSksIF90ZW1peihtZXRpbihiKSlbOjkwXV0g
Zm9yIGIgaW4gYmFzbGlrbGFyXVs6NDAwXX0KICAgIGRpemlsZXIgPSBjb2xsZWN0aW9ucy5kZWZhdWx0ZGljdChsaXN0KSAgIyAi
MS4gS1VEU8SwIEhBRMSwUyIsICJCaXJpbmNpIFPDtnoiIGRlxJ9pbDsgeWFsbsSxeiByYWthbWzEsSBiYcWfbMSxa2xhcgogICAg
Zm9yIGIgaW4gYmFzbGlrbGFyOgogICAgICAgIG0gPSByZS5tYXRjaChyIl5ccyooXGR7MSwzfSlccypbLilcLeKAk+KAlDpdP1xz
KiguKikkIiwgX3RlbWl6KG1ldGluKGIpKSkKICAgICAgICBpZiBtIGFuZCBtLmdyb3VwKDIpOgogICAgICAgICAgICBhbmFodGFy
ID0gcmUuc3ViKHIiW1xXXGRfXSsiLCAiICIsIG0uZ3JvdXAoMikpLnN0cmlwKCkubG93ZXIoKVs6NDBdCiAgICAgICAgICAgIGRp
emlsZXJbYW5haHRhcl0uYXBwZW5kKGludChtLmdyb3VwKDEpKSkKICAgIHNvcnVuID0gW10KICAgIGZvciBhbmFodGFyLCBub2xh
ciBpbiBkaXppbGVyLml0ZW1zKCk6CiAgICAgICAgaWYgbGVuKG5vbGFyKSA8IDM6CiAgICAgICAgICAgIGNvbnRpbnVlCiAgICAg
ICAgZWtzaWsgPSBzb3J0ZWQoc2V0KHJhbmdlKG1pbihub2xhciksIG1heChub2xhcikgKyAxKSkgLSBzZXQobm9sYXIpKQogICAg
ICAgIHRla3JhciA9IHNvcnRlZChuIGZvciBuLCBjIGluIGNvbGxlY3Rpb25zLkNvdW50ZXIobm9sYXIpLml0ZW1zKCkgaWYgYyA+
IDEpCiAgICAgICAgZ2VyaSA9IHN1bSgxIGZvciB4LCB5IGluIHppcChub2xhciwgbm9sYXJbMTpdKSBpZiB5IDwgeCkKICAgICAg
ICBpZiBla3NpayBvciB0ZWtyYXIgb3IgZ2VyaToKICAgICAgICAgICAgc29ydW4uYXBwZW5kKHsiZGl6aSI6IGFuYWh0YXIsICJh
ZGV0IjogbGVuKG5vbGFyKSwgImFyYWxpayI6IFttaW4obm9sYXIpLCBtYXgobm9sYXIpXSwgImVrc2lrIjogZWtzaWtbOjUwXSwK
ICAgICAgICAgICAgICAgICAgICAgICAgICAidGVrcmFyIjogdGVrcmFyWzoyMF0sICJnZXJpX2dpZGVuIjogZ2VyaX0pCiAgICB5
YXBpWyJudW1hcmFsaV9iYXNsaWtfc29ydW5sYXJpIl0gPSBzb3J1bgogICAgeWFwaVsibnVtYXJhbGlfYmFzbGlrX2RpemlsZXJp
Il0gPSB7YTogbGVuKG4pIGZvciBhLCBuIGluIGRpemlsZXIuaXRlbXMoKSBpZiBsZW4obikgPj0gM30KICAgIGV0aWtldGxlciA9
IFtzLmdldCgibm8iKSBmb3IgYiBpbiBibG9rbGFyIGZvciBzIGluIChiLmdldCgic2F5ZmFsYXIiKSBvciBbXSldCiAgICBzYXlp
bGFyID0gW19zYXlpKGUpIGZvciBlIGluIGV0aWtldGxlciBpZiBfc2F5aShlKSBpcyBub3QgTm9uZV0KICAgIGF0bGFtYSA9IFtb
eCwgeV0gZm9yIHgsIHkgaW4gemlwKHNheWlsYXIsIHNheWlsYXJbMTpdKSBpZiB5ICE9IHggKyAxXQogICAgeWFwaVsic2F5ZmEi
XSA9IHsiaXNhcmV0IjogbGVuKGV0aWtldGxlciksICJpbGsiOiBzYXlpbGFyWzBdIGlmIHNheWlsYXIgZWxzZSBOb25lLAogICAg
ICAgICAgICAgICAgICAgICAic29uIjogc2F5aWxhclstMV0gaWYgc2F5aWxhciBlbHNlIE5vbmUsICJhdGxhbWEiOiBhdGxhbWFb
OjQwXSwgImF0bGFtYV9zYXlpc2kiOiBsZW4oYXRsYW1hKSwKICAgICAgICAgICAgICAgICAgICAgInNheWlzYWxfb2xtYXlhbiI6
IFtlIGZvciBlIGluIGV0aWtldGxlciBpZiBfc2F5aShlKSBpcyBOb25lIGFuZCBub3QgcmUuZnVsbG1hdGNoKHIiW2l2eGxjZG1d
ezEsNn0iLCBlIG9yICIiLCByZS5JKV1bOjIwXX0KICAgIGlzYXJldGxlciA9IFtnIGZvciBiIGluIGJsb2tsYXIgZm9yIGcgaW4g
cmUuZmluZGFsbChyIlx7XHsoblxkezQsfSlcfVx9IiwgbWV0aW4oYikpXQogICAgZGlwbm90bGFyID0ga2l0LmdldCgiZGlwbm90
bGFyIikgb3Ige30KICAgIHlhcGlbImRpcG5vdCJdID0geyJpc2FyZXQiOiBsZW4oaXNhcmV0bGVyKSwgIm1ldGluIjogbGVuKGRp
cG5vdGxhciksCiAgICAgICAgICAgICAgICAgICAgICAibWV0bmlfb2xtYXlhbl9pc2FyZXQiOiBsZW4oW2cgZm9yIGcgaW4gaXNh
cmV0bGVyIGlmIGcgbm90IGluIGRpcG5vdGxhcl0pLAogICAgICAgICAgICAgICAgICAgICAgImF5bmlfaXNhcmV0X3Rla3JhciI6
IGxlbihpc2FyZXRsZXIpIC0gbGVuKHNldChpc2FyZXRsZXIpKX0KICAgICMgZGlwbm90YSBiZW56ZXllbiBnw7Z2ZGUgcGFyYWdy
YWbEsSAoIjEyIEJ1aMOicsOuLCBUZXZow65kLCAzNSIgLyAiMS0gQmsuIC4uLiIpOiBkaXBub3QgZ8O2dmRleWUga2FyxLHFn23E
scWfIG9sYWJpbGlyCiAgICBrYXJpc2FuID0gW10KICAgIGZvciBiIGluIHBhcmFncmFmbGFyOgogICAgICAgIHQgPSBfdGVtaXoo
bWV0aW4oYikpCiAgICAgICAgaWYgcmUubWF0Y2gociJeKFxkezEsM318XCopXHMqWy0uKV0/XHMrXFMiLCB0KSBhbmQgbGVuKHQp
IDwgMzAwIGFuZCBcCiAgICAgICAgICAgICAgICByZS5zZWFyY2gociJcYihia1wufGJrelwufGFcLmdcLmV8YWdlXC58c1wuXHMq
XGR8Y1wuXHMqXGR8QnVow6Jyw658QnVoYXJpfE3DvHNsaW18VGlybWl6w658VGlybWl6aXxFYsO7IETDonbDu2R8TmVzw6LDrnzE
sGJuIE3DomNlfE3DvHNuZWR8aGFkaXMgbm8pIiwgdCwgcmUuSSk6CiAgICAgICAgICAgIGthcmlzYW4uYXBwZW5kKHRbOjE0MF0p
CiAgICB5YXBpWyJkaXBub3RhX2JlbnpleWVuX3BhcmFncmFmIl0gPSBrYXJpc2FuWzozMF0KICAgIHJbInlhcGkiXSA9IHlhcGkK
ICAgICMgLS0tIMWfw7xwaGVsaSBrZWxpbWVsZXIgdmUgcGFyYWdyYWZsYXIgKHlhbG7EsXogVMO8cmvDp2Uga2l0YXB0YSkgLS0t
CiAgICBzdXBoZWxpLCBvcm5laywgc3VwaGVsaV9wID0gY29sbGVjdGlvbnMuQ291bnRlcigpLCB7fSwgW10KICAgIGlmIGRpbCA9
PSAidHIiOgogICAgICAgIHNvbl9zYXlmYSA9IE5vbmUKICAgICAgICBoZXBzaSA9IFsoYiwgIm1ldGluIikgZm9yIGIgaW4gYmxv
a2xhcl0gKyBbKHsibWV0aW4iOiBkLmdldCgibWV0aW4iKX0sICJkaXBub3QiKSBmb3IgZCBpbiBkaXBub3RsYXIudmFsdWVzKCld
CiAgICAgICAgZm9yIHNpcmEsIChiLCB5ZXIpIGluIGVudW1lcmF0ZShoZXBzaSk6CiAgICAgICAgICAgIGhhbSA9IG1ldGluKGIp
CiAgICAgICAgICAgIGZvciBzIGluIGIuZ2V0KCJzYXlmYWxhciIpIG9yIFtdOgogICAgICAgICAgICAgICAgc29uX3NheWZhID0g
cy5nZXQoIm5vIikgb3Igc29uX3NheWZhCiAgICAgICAgICAgIHQgPSBfdGVtaXooaGFtKQogICAgICAgICAgICBrZWwgPSBbdyBm
b3IgdyBpbiBfS0VMSU1FLmZpbmRhbGwodCkgaWYgbm90IF9BUkFQLnNlYXJjaCh3KV0KICAgICAgICAgICAgZ2VjZXJzaXogPSBb
dyBmb3IgdyBpbiBrZWwgaWYgbm90IF9nZWNlcmxpKF9rdWN1ayh3KSldCiAgICAgICAgICAgIGZvciB3IGluIGdlY2Vyc2l6Ogog
ICAgICAgICAgICAgICAgazIgPSBfa3VjdWsodykKICAgICAgICAgICAgICAgIHN1cGhlbGlbazJdICs9IDEKICAgICAgICAgICAg
ICAgIGlmIGsyIG5vdCBpbiBvcm5lazoKICAgICAgICAgICAgICAgICAgICBpID0gdC5maW5kKHcpCiAgICAgICAgICAgICAgICAg
ICAgb3JuZWtbazJdID0geyJzYXlmYSI6IHNvbl9zYXlmYSwgImJhZ2xhbSI6IHRbbWF4KDAsIGkgLSA1MCk6aSArIGxlbih3KSAr
IDUwXX0KICAgICAgICAgICAgaGFyZiA9IHN1bSgxIGZvciBjIGluIHQgaWYgYy5pc2FscGhhKCkpCiAgICAgICAgICAgIGRvbHUg
PSBsZW4ocmUuc3ViKHIiXHMiLCAiIiwgdCkpCiAgICAgICAgICAgIGlmIChsZW4oa2VsKSA+PSAyIGFuZCBsZW4oZ2VjZXJzaXop
ID49IDAuNiAqIGxlbihrZWwpKSBvciAoZG9sdSA+PSA4IGFuZCBoYXJmIDwgMC42ICogZG9sdSBhbmQgbm90IF9BUkFQLnNlYXJj
aCh0KSk6CiAgICAgICAgICAgICAgICBzdXBoZWxpX3AuYXBwZW5kKHsic2lyYSI6IHNpcmEsICJ5ZXIiOiB5ZXIsICJzYXlmYSI6
IHNvbl9zYXlmYSwgIm1ldGluIjogdFs6MTYwXX0pCiAgICByWyJzdXBoZWxpX2tlbGltZSJdID0gW3sia2VsaW1lIjogdywgImFk
ZXQiOiBjLCAqKm9ybmVrW3ddfSBmb3IgdywgYyBpbiBzdXBoZWxpLm1vc3RfY29tbW9uKDQwMCldCiAgICByWyJzdXBoZWxpX2tl
bGltZV90b3BsYW0iXSA9IHsiZmFya2xpIjogbGVuKHN1cGhlbGkpLCAiZ2VjaXMiOiBzdW0oc3VwaGVsaS52YWx1ZXMoKSl9CiAg
ICByWyJzdXBoZWxpX3BhcmFncmFmIl0gPSBzdXBoZWxpX3BbOjgwXQogICAgIyAtLS0gZGXEn2nFn2lrbGlrbGVyIHZlIHNpbGlu
ZW5sZXIgLS0tCiAgICBkZyA9IHNvcnRlZCgoKHgsIHksIHllciwgZCkgZm9yICh4LCB5LCB5ZXIpLCBkIGluIChrLmdldCgiZGVn
aXNpa2xpayIpIG9yIHt9KS5pdGVtcygpKSwga2V5PWxhbWJkYSB0OiAtdFszXVsiYWRldCJdKQogICAgclsiZGVnaXNpa2xpayJd
ID0gW3sib25jZSI6IHgsICJzb25yYSI6IHksICJ5ZXIiOiB5ZXIsICoqZH0gZm9yIHgsIHksIHllciwgZCBpbiBkZ1s6MTUwMF1d
CiAgICByWyJkZWdpc2lrbGlrX3RvcGxhbSJdID0geyJmYXJrbGkiOiBsZW4oZGcpLCAiZ2VjaXMiOiBzdW0odFszXVsiYWRldCJd
IGZvciB0IGluIGRnKSwgIm5va3RhbGFtYV9ib3NsdWsiOiBrLmdldCgibm9rdGFsYW1hIiwgMCl9CiAgICByWyJzaWxpbmVuIl0g
PSB7dHVyOiBbeyJtZXRpbiI6IHQsICJhZGV0IjogY30gZm9yIHQsIGMgaW4gc2F5YWMubW9zdF9jb21tb24oMjAwKV0KICAgICAg
ICAgICAgICAgICAgICBmb3IgdHVyLCBzYXlhYyBpbiAoay5nZXQoInNpbGluZW4iKSBvciB7fSkuaXRlbXMoKX0KICAgIHJldHVy
biByCgoKZGVmIGtheWRldChrbGFzb3IsIHJhcG9yKToKICAgIGlmIG5vdCByYXBvciBvciBub3Qga2xhc29yOgogICAgICAgIHJl
dHVybgogICAgb3MubWFrZWRpcnMoa2xhc29yLCBleGlzdF9vaz1UcnVlKQogICAgd2l0aCBvcGVuKG9zLnBhdGguam9pbihrbGFz
b3IsICJyYXBvci5qc29uLnRtcCIpLCAidyIsIGVuY29kaW5nPSJ1dGYtOCIpIGFzIGY6CiAgICAgICAganNvbi5kdW1wKHJhcG9y
LCBmLCBlbnN1cmVfYXNjaWk9RmFsc2UsIGluZGVudD0xKQogICAgb3MucmVwbGFjZShvcy5wYXRoLmpvaW4oa2xhc29yLCAicmFw
b3IuanNvbi50bXAiKSwgb3MucGF0aC5qb2luKGtsYXNvciwgInJhcG9yLmpzb24iKSkKICAgIHdpdGggb3Blbihvcy5wYXRoLmpv
aW4oa2xhc29yLCAicmFwb3IudHh0IiksICJ3IiwgZW5jb2Rpbmc9InV0Zi04IikgYXMgZjoKICAgICAgICBmLndyaXRlKG1ldGlu
X2hhbGkocmFwb3IpKQoKCiMgPT09PT09PT09PT09PT09PT09PT09PT0gb2t1bnVyIG1ldGluID09PT09PT09PT09PT09PT09PT09
PT09CmRlZiBtZXRpbl9oYWxpKHIsIGtpc2E9RmFsc2UpOgogICAgaWYgci5nZXQoImhhdGEiKToKICAgICAgICByZXR1cm4gZiJS
QVBPUiBIQVRBU0k6IHtyWydoYXRhJ119XG4iCiAgICBzID0gW10KICAgIGtpLCBjLCBvID0gclsia2l0YXAiXSwgclsiY2lrYXJt
YSJdLCByWyJvemV0Il0KICAgIHMuYXBwZW5kKGYiIyMjIHtraVsnYWQnXX0g4oCUIHtraVsneWF6YXInXX0gIFt7a2lbJ3R1cidd
fSwgZGlsIHtraVsnZGlsJ119XSAga2F5bmFrOiB7a2lbJ2theW5hayddfSIpCiAgICBzLmFwcGVuZChmInNheWZhIHtjLmdldCgn
c2F5ZmEnKX0sIE9DUiBzYXlmYSB7Yy5nZXQoJ29jcl9zYXlmYScpfSAoe2MuZ2V0KCdvY3JfbW90b3J1Jykgb3IgJy0nfSksIGJv
enVrIGthdG1hbjoge2MuZ2V0KCdib3p1a19rYXRtYW4nKX0sICIKICAgICAgICAgICAgIGYib25hcsSxbToge2MuZ2V0KCdvbmFy
aW0nKX0iKQogICAgcy5hcHBlbmQoZiJwYXJhZ3JhZiB7b1sncGFyYWdyYWYnXX0sIGJhxZ9sxLFrIHtvWydiYXNsaWsnXX0gKHNl
dml5ZSB7b1snc2V2aXllJ119KSwga2VsaW1lIHtvWydrZWxpbWUnXX0sIGRpcG5vdCB7b1snZGlwbm90J119IikKICAgIHkgPSBy
WyJ5YXBpIl0KICAgIHMuYXBwZW5kKCItLSBZYXDEsSIpCiAgICBmb3IgZCBpbiB5WyJudW1hcmFsaV9iYXNsaWtfc29ydW5sYXJp
Il06CiAgICAgICAgcy5hcHBlbmQoZiIgIE5VTUFSQUxJIEJBxZ5MSUsgJ3tkWydkaXppJ119Jzoge2RbJ2FkZXQnXX0gYmHFn2zE
sWsge2RbJ2FyYWxpayddfSwgZWtzaWsge2RbJ2Vrc2lrJ119LCB0ZWtyYXIge2RbJ3Rla3JhciddfSwgZ2VyaSBnaWRlbiB7ZFsn
Z2VyaV9naWRlbiddfSIpCiAgICBpZiB5WyJudW1hcmFsaV9iYXNsaWtfZGl6aWxlcmkiXToKICAgICAgICBzLmFwcGVuZChmIiAg
bnVtYXJhbMSxIGJhxZ9sxLFrIGRpemlsZXJpOiB7eVsnbnVtYXJhbGlfYmFzbGlrX2RpemlsZXJpJ119IikKICAgIHN5ID0geVsi
c2F5ZmEiXQogICAgcy5hcHBlbmQoZiIgIHNheWZhIGnFn2FyZXRpIHtzeVsnaXNhcmV0J119ICh7c3lbJ2lsayddfeKAk3tzeVsn
c29uJ119KSwgYXRsYW1hIHtzeVsnYXRsYW1hX3NheWlzaSddfToge3N5WydhdGxhbWEnXVs6MTVdfSIKICAgICAgICAgICAgICsg
KGYiLCBzYXnEsXNhbCBvbG1heWFuOiB7c3lbJ3NheWlzYWxfb2xtYXlhbiddfSIgaWYgc3lbInNheWlzYWxfb2xtYXlhbiJdIGVs
c2UgIiIpKQogICAgZG4gPSB5WyJkaXBub3QiXQogICAgcy5hcHBlbmQoZiIgIGRpcG5vdCBpxZ9hcmV0aSB7ZG5bJ2lzYXJldCdd
fSwgZGlwbm90IG1ldG5pIHtkblsnbWV0aW4nXX0sIG1ldG5pIG9sbWF5YW4gacWfYXJldCB7ZG5bJ21ldG5pX29sbWF5YW5faXNh
cmV0J119LCB0ZWtyYXIge2RuWydheW5pX2lzYXJldF90ZWtyYXInXX0iKQogICAgZm9yIHQgaW4geVsiZGlwbm90YV9iZW56ZXll
bl9wYXJhZ3JhZiJdWzoxMCBpZiBraXNhIGVsc2UgMzBdOgogICAgICAgIHMuYXBwZW5kKGYiICBExLBQTk9UQSBCRU5aRVlFTiBQ
QVJBR1JBRjoge3R9IikKICAgIGlmIG5vdCBraXNhOgogICAgICAgIHMuYXBwZW5kKCIgIGJhxZ9sxLFrbGFyOiAiICsgIiB8ICIu
am9pbihmIntzdn06e3R9IiBmb3Igc3YsIHQgaW4geVsiYmFzbGlrbGFyIl1bOjEyMF0pKQogICAgZHQgPSByWyJkZWdpc2lrbGlr
X3RvcGxhbSJdCiAgICBzLmFwcGVuZChmIi0tIERlxJ9pxZ9pa2xpa2xlcjoge2R0WydmYXJrbGknXX0gZmFya2zEsSwge2R0Wydn
ZWNpcyddfSBrZXogKGF5csSxY2EgYm/Fn2x1ay9ub2t0YWxhbWEge2R0Wydub2t0YWxhbWFfYm9zbHVrJ119KSIpCiAgICBmb3Ig
ZCBpbiByWyJkZWdpc2lrbGlrIl1bOjYwIGlmIGtpc2EgZWxzZSA0MDBdOgogICAgICAgIHMuYXBwZW5kKGYiICB7ZFsnYWRldCdd
OjR9ICB7ZFsnb25jZSddfSAgLT4gIHtkWydzb25yYSddfSAgIFt7ZFsneWVyJ119LCBzLntkWydzYXlmYSddfV0gIMKrIHtkWydi
YWdsYW0nXVs6MTAwXX0gwrsiKQogICAgZm9yIHR1ciwgbGlzdGUgaW4gclsic2lsaW5lbiJdLml0ZW1zKCk6CiAgICAgICAgcy5h
cHBlbmQoZiItLSBTaWxpbmVuICh7dHVyfSk6IHtzdW0oeFsnYWRldCddIGZvciB4IGluIGxpc3RlKX0iKQogICAgICAgIGZvciB4
IGluIGxpc3RlWzoxNSBpZiBraXNhIGVsc2UgNjBdOgogICAgICAgICAgICBzLmFwcGVuZChmIiAge3hbJ2FkZXQnXTo0fSAge3hb
J21ldGluJ11bOjE0MF19IikKICAgIHN0ID0gclsic3VwaGVsaV9rZWxpbWVfdG9wbGFtIl0KICAgIHMuYXBwZW5kKGYiLS0gxZ7D
vHBoZWxpIGtlbGltZWxlciAoc8O2emzDvGt0ZSB5b2spOiB7c3RbJ2ZhcmtsaSddfSBmYXJrbMSxLCB7c3RbJ2dlY2lzJ119IGtl
eiIpCiAgICBmb3IgZCBpbiByWyJzdXBoZWxpX2tlbGltZSJdWzo4MCBpZiBraXNhIGVsc2UgNDAwXToKICAgICAgICBzLmFwcGVu
ZChmIiAge2RbJ2FkZXQnXTo0fSAge2RbJ2tlbGltZSddfSAgIFtzLntkWydzYXlmYSddfV0gIMKrIHtkWydiYWdsYW0nXVs6MTEw
XX0gwrsiKQogICAgcy5hcHBlbmQoZiItLSDFnsO8cGhlbGkgcGFyYWdyYWZsYXI6IHtsZW4oclsnc3VwaGVsaV9wYXJhZ3JhZidd
KX0iKQogICAgZm9yIHAgaW4gclsic3VwaGVsaV9wYXJhZ3JhZiJdWzoyMCBpZiBraXNhIGVsc2UgODBdOgogICAgICAgIHMuYXBw
ZW5kKGYiICAje3BbJ3NpcmEnXX0gW3twWyd5ZXInXX0sIHMue3BbJ3NheWZhJ119XSAge3BbJ21ldGluJ11bOjE0MF19IikKICAg
IHJldHVybiAiXG4iLmpvaW4ocykgKyAiXG4iCgoKZGVmIF9raXRhcGxhcl9rbGFzb3J1KCk6CiAgICByZXR1cm4gb3MucGF0aC5q
b2luKG9zLmVudmlyb24uZ2V0KCJEQVRBX0RJUiIsICIvZGF0YSIpLCAia2l0YXBsYXIiKQoKCmRlZiB0b3BsdShrbGFzb3I9Tm9u
ZSwga2lzYT1UcnVlKToKICAgICIiIkLDvHTDvG4ga2l0YXBsYXLEsW4gcmFwb3JsYXLEsTogw7ZuY2Uga2l0YXBsYXIgYXJhc8Sx
IG9ydGFrIGRlxJ9pxZ9pa2xpa2xlciAoYXluxLEga3VyYWwgYmlyw6dvayBraXRhYsSxIGV0a2lsaXlvcnNhKSwgc29ucmEKICAg
IGhlciBraXRhYsSxbiBrxLFzYSByYXBvcnUuIiIiCiAgICBrbGFzb3IgPSBrbGFzb3Igb3IgX2tpdGFwbGFyX2tsYXNvcnUoKQog
ICAgcmFwb3JsYXIgPSBbXQogICAgZm9yIGtpZCBpbiBzb3J0ZWQob3MubGlzdGRpcihrbGFzb3IpKSBpZiBvcy5wYXRoLmlzZGly
KGtsYXNvcikgZWxzZSBbXToKICAgICAgICB5b2wgPSBvcy5wYXRoLmpvaW4oa2xhc29yLCBraWQsICJyYXBvci5qc29uIikKICAg
ICAgICBpZiBvcy5wYXRoLmV4aXN0cyh5b2wpOgogICAgICAgICAgICB0cnk6CiAgICAgICAgICAgICAgICByYXBvcmxhci5hcHBl
bmQoKGtpZCwganNvbi5sb2FkKG9wZW4oeW9sLCBlbmNvZGluZz0idXRmLTgiKSkpKQogICAgICAgICAgICBleGNlcHQgRXhjZXB0
aW9uOgogICAgICAgICAgICAgICAgcGFzcwogICAgcyA9IFtmIkRFRFBMQVkgVE9QTFUgUkFQT1Ig4oCUIHtsZW4ocmFwb3JsYXIp
fSBraXRhcCDigJQge3RpbWUuc3RyZnRpbWUoJyVZLSVtLSVkICVIOiVNJyl9Il0KICAgIG9ydGFrID0gY29sbGVjdGlvbnMuZGVm
YXVsdGRpY3QobGFtYmRhOiBbMCwgc2V0KCldKQogICAgZm9yIGtpZCwgciBpbiByYXBvcmxhcjoKICAgICAgICBmb3IgZCBpbiBy
LmdldCgiZGVnaXNpa2xpayIsIFtdKToKICAgICAgICAgICAgbyA9IG9ydGFrWyhkWyJvbmNlIl0sIGRbInNvbnJhIl0pXQogICAg
ICAgICAgICBvWzBdICs9IGRbImFkZXQiXQogICAgICAgICAgICBvWzFdLmFkZChraWQpCiAgICBzLmFwcGVuZCgiPT0gQmlyZGVu
IMOnb2sga2l0YXB0YSB5YXDEsWxhbiBkZcSfacWfaWtsaWtsZXIgKGtpdGFwIHNhecSxc8SxLCB0b3BsYW0pIikKICAgIGZvciAo
eCwgeSksIChuLCBraXRhcGxhcikgaW4gc29ydGVkKG9ydGFrLml0ZW1zKCksIGtleT1sYW1iZGEgdDogKC1sZW4odFsxXVsxXSks
IC10WzFdWzBdKSlbOjE1MF06CiAgICAgICAgaWYgbGVuKGtpdGFwbGFyKSA+PSAyOgogICAgICAgICAgICBzLmFwcGVuZChmIiAg
e2xlbihraXRhcGxhcik6M30ga2l0YXAge246NX0gIHt4fSAgLT4gIHt5fSIpCiAgICBmb3Iga2lkLCByIGluIHJhcG9ybGFyOgog
ICAgICAgIHMuYXBwZW5kKCIiKQogICAgICAgIHMuYXBwZW5kKGYiW3traWR9XSIpCiAgICAgICAgcy5hcHBlbmQobWV0aW5faGFs
aShyLCBraXNhPWtpc2EpKQogICAgcmV0dXJuICJcbiIuam9pbihzKSArICJcbiIKCgojID09PT09PT09PT09PT09PT09PT09PT09
IGt1cnUgZGVuZW1lID09PT09PT09PT09PT09PT09PT09PT09CmRlZiBfa2VsaW1lX2ZhcmtpKGVza2ksIHllbmkpOgogICAgYyA9
IGNvbGxlY3Rpb25zLkNvdW50ZXIoKQogICAgYSwgYiA9IGVza2kuc3BsaXQoKSwgeWVuaS5zcGxpdCgpCiAgICBmb3Igb3AsIGkx
LCBpMiwgajEsIGoyIGluIGRpZmZsaWIuU2VxdWVuY2VNYXRjaGVyKE5vbmUsIGEsIGIsIGF1dG9qdW5rPUZhbHNlKS5nZXRfb3Bj
b2RlcygpOgogICAgICAgIGlmIG9wICE9ICJlcXVhbCI6CiAgICAgICAgICAgIHgsIHkgPSBfdGVtaXooIiAiLmpvaW4oYVtpMTpp
Ml0pKVs6NjBdLCBfdGVtaXooIiAiLmpvaW4oYltqMTpqMl0pKVs6NjBdCiAgICAgICAgICAgIGlmIHggIT0geToKICAgICAgICAg
ICAgICAgIGNbKHgsIHkpXSArPSAxCiAgICByZXR1cm4gYwoKCmRlZiBrdXJ1X2RlbmVtZShraWRsZXI9Tm9uZSwgY2lrdGk9Tm9u
ZSk6CiAgICAiIiJLaXRhcGxhcsSxIGtheW5hayBkb3N5YWxhcsSxbmRhbiB5ZW5pIGtvZGxhIHllbmlkZW4gacWfbGVyOyBPQ1Ig
eWFsbsSxeiDDtm5iZWxsZWt0ZW4gKMO2bmJlbGxla3RlIG9sbWF5YW4gc2F5ZmEgdmFyc2EKICAgIGtpdGFwIGF0bGFuxLFyKS4g
SGnDp2JpciBraXRhYmEgeWF6bWF6LiBIZXIga2l0YXAgacOnaW4gcmFwb3IgdmUgxZ9pbWRpa2kga2l0YXAuanNvbiBpbGUgVMO8
cmvDp2UgbWV0aW4gZmFya8SxIHlhesSxbMSxci4iIiIKICAgIGZyb20ga3V0dXBoYW5lIGltcG9ydCBrYXluYWssIGtpdGFwIGFz
IEsKICAgIGtsYXNvciA9IF9raXRhcGxhcl9rbGFzb3J1KCkKICAgIGNpa3RpID0gY2lrdGkgb3Igb3MucGF0aC5qb2luKG9zLmVu
dmlyb24uZ2V0KCJEQVRBX0RJUiIsICIvZGF0YSIpLCAia3VydV9kZW5lbWUiKQogICAgb3MubWFrZWRpcnMoY2lrdGksIGV4aXN0
X29rPVRydWUpCiAgICBvemV0ID0gW2YiS1VSVSBERU5FTUUg4oCUIHt0aW1lLnN0cmZ0aW1lKCclWS0lbS0lZCAlSDolTScpfSJd
CiAgICBmb3Iga2lkIGluIHNvcnRlZChraWRsZXIgb3Igb3MubGlzdGRpcihrbGFzb3IpKToKICAgICAgICB5b2xfayA9IG9zLnBh
dGguam9pbihrbGFzb3IsIGtpZCwgImtpdGFwLmpzb24iKQogICAgICAgIGlmIG5vdCBvcy5wYXRoLmV4aXN0cyh5b2xfayk6CiAg
ICAgICAgICAgIGNvbnRpbnVlCiAgICAgICAgdHJ5OgogICAgICAgICAgICBlc2tpID0gSy55dWtsZSh5b2xfaykKICAgICAgICAg
ICAga2F5bmFrX3lvbCA9ICgoZXNraS5nZXQoImt1bnllIikgb3Ige30pLmdldCgia2F5bmFrIikgb3Ige30pLmdldCgieW9sIikK
ICAgICAgICAgICAgaWYgbm90IGtheW5ha195b2wgb3Igbm90IG9zLnBhdGguZXhpc3RzKGtheW5ha195b2wpOgogICAgICAgICAg
ICAgICAgb3pldC5hcHBlbmQoZiJbe2tpZH1dIEFUTEFOREk6IGtheW5hayBkb3N5YSB5b2sgKHtrYXluYWtfeW9sfSkiKQogICAg
ICAgICAgICAgICAgY29udGludWUKICAgICAgICAgICAgaWYga2F5bmFrLm9jcl9nZXJla2lyKGtheW5ha195b2wpOgogICAgICAg
ICAgICAgICAgb3pldC5hcHBlbmQoZiJbe2tpZH1dIEFUTEFOREk6IE9DUiDDtm5iZWxsZWt0ZSBkZcSfaWwgKMO2bmNlIGtpdGFw
IGJpciBrZXogacWfbGVubWVsaSkiKQogICAgICAgICAgICAgICAgY29udGludWUKICAgICAgICAgICAgYmFzID0gdGltZS50aW1l
KCkKICAgICAgICAgICAgeWVuaSA9IGtheW5hay5jZXZpcihrYXluYWtfeW9sLCBOb25lLCB7InlvbCI6IGtheW5ha195b2x9KQog
ICAgICAgICAgICByYXBvciA9IGFsKCkgb3Ige30KICAgICAgICAgICAgaGVkZWYgPSBvcy5wYXRoLmpvaW4oY2lrdGksIGtpZCkK
ICAgICAgICAgICAga2F5ZGV0KGhlZGVmLCByYXBvcikKICAgICAgICAgICAgZGlsID0gKHllbmkuZ2V0KCJrdW55ZSIpIG9yIHt9
KS5nZXQoImFzaWxfZGlsIiwgInRyIikKICAgICAgICAgICAgdG0gPSBsYW1iZGEga2l0OiAiXG4iLmpvaW4oX3RlbWl6KChiLmdl
dCgibWV0aW4iKSBvciB7fSkuZ2V0KGRpbCkgb3IgKGIuZ2V0KCJtZXRpbiIpIG9yIHt9KS5nZXQoInRyIikgb3IgIiIpCiAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIGZvciBiIGluIGtpdC5nZXQoImJsb2tsYXIiLCBbXSkpCiAgICAgICAg
ICAgIGZhcmtfYyA9IF9rZWxpbWVfZmFya2kodG0oZXNraSksIHRtKHllbmkpKQogICAgICAgICAgICBzYXRpciA9IFtmIlt7a2lk
fV0ge3RpbWUudGltZSgpIC0gYmFzOi4wZn0gc24sIMWfaW1kaWtpIGtpdGFwbGEge3N1bShmYXJrX2MudmFsdWVzKCkpfSBrZWxp
bWUgZmFya8SxIl0KICAgICAgICAgICAgZm9yICh4LCB5KSwgbiBpbiBmYXJrX2MubW9zdF9jb21tb24oNjApOgogICAgICAgICAg
ICAgICAgc2F0aXIuYXBwZW5kKGYiICB7bjo0fSAge3ggb3IgJ+KIhSd9ICAtPiAge3kgb3IgJ+KIhSd9IikKICAgICAgICAgICAg
d2l0aCBvcGVuKG9zLnBhdGguam9pbihoZWRlZiwgImZhcmsudHh0IiksICJ3IiwgZW5jb2Rpbmc9InV0Zi04IikgYXMgZjoKICAg
ICAgICAgICAgICAgIGYud3JpdGUoIlxuIi5qb2luKFtzYXRpclswXV0gKyBbZiIgIHtuOjR9ICB7eCBvciAn4oiFJ30gIC0+ICB7
eSBvciAn4oiFJ30iIGZvciAoeCwgeSksIG4gaW4gZmFya19jLm1vc3RfY29tbW9uKCldKSArICJcbiIpCiAgICAgICAgICAgIG96
ZXQgKz0gc2F0aXIKICAgICAgICAgICAgcHJpbnQoc2F0aXJbMF0sIGZpbGU9c3lzLnN0ZGVyciwgZmx1c2g9VHJ1ZSkKICAgICAg
ICBleGNlcHQgRXhjZXB0aW9uIGFzIGU6CiAgICAgICAgICAgIG96ZXQuYXBwZW5kKGYiW3traWR9XSBIQVRBOiB7dHlwZShlKS5f
X25hbWVfX306IHtzdHIoZSlbOjIwMF19IikKICAgICAgICAgICAgcHJpbnQob3pldFstMV0sIGZpbGU9c3lzLnN0ZGVyciwgZmx1
c2g9VHJ1ZSkKICAgIG1ldGluID0gIlxuIi5qb2luKG96ZXQpICsgIlxuIgogICAgd2l0aCBvcGVuKG9zLnBhdGguam9pbihjaWt0
aSwgIm96ZXQudHh0IiksICJ3IiwgZW5jb2Rpbmc9InV0Zi04IikgYXMgZjoKICAgICAgICBmLndyaXRlKG1ldGluKQogICAgd2l0
aCBvcGVuKG9zLnBhdGguam9pbihjaWt0aSwgInRvcGx1LnR4dCIpLCAidyIsIGVuY29kaW5nPSJ1dGYtOCIpIGFzIGY6CiAgICAg
ICAgZi53cml0ZSh0b3BsdShjaWt0aSkpCiAgICByZXR1cm4gbWV0aW4KCgppZiBfX25hbWVfXyA9PSAiX19tYWluX18iOgogICAg
a29tdXQgPSBzeXMuYXJndlsxXSBpZiBsZW4oc3lzLmFyZ3YpID4gMSBlbHNlICJ0b3BsdSIKICAgIGlmIGtvbXV0ID09ICJ0b3Bs
dSI6CiAgICAgICAgc3lzLnN0ZG91dC53cml0ZSh0b3BsdShraXNhPSItLXV6dW4iIG5vdCBpbiBzeXMuYXJndikpCiAgICBlbGlm
IGtvbXV0ID09ICJrdXJ1IjoKICAgICAgICBzeXMuc3Rkb3V0LndyaXRlKGt1cnVfZGVuZW1lKFthIGZvciBhIGluIHN5cy5hcmd2
WzI6XSBpZiBub3QgYS5zdGFydHN3aXRoKCItIildIG9yIE5vbmUpKQogICAgZWxzZToKICAgICAgICBzeXMuZXhpdCgia3VsbGFu
xLFtOiBweXRob24gLW0ga3V0dXBoYW5lLnJhcG9yIHRvcGx1IFstLXV6dW5dIHwga3VydSBba2l0YXAga2ltbGnEn2kgLi4uXSIp
Cg==
""",
    "tests/test_rapor.py": """
IiIiMC41LjIzIGdlcmlsZW1lIHRlc3RpOiBraXRhcCByYXBvcnUuIFJhcG9yIG1ldG5pIERFxJ7EsMWeVMSwUk1FWiwgeWFsbsSx
eiBrYXlkZWRlcjsgaGF0YSB2ZXJzZSBiaWxlIGtpdGFwIGnFn2xlbmlyLgpEZcSfacWfaWtsaWssIHNpbGluZW4sIHlhcMSxIGRl
bmV0aW1pIChudW1hcmFsxLEgYmHFn2zEsWsgZWtzaWtsZXJpLCBzYXlmYSBhdGxhbWFzxLEsIGRpcG5vdCBlxZ9sZcWfbWVzaSks
IMWfw7xwaGVsaSBrZWxpbWUvcGFyYWdyYWYuIiIiCmltcG9ydCBqc29uLCBvcywgc3lzLCB0ZW1wZmlsZQpzeXMucGF0aC5pbnNl
cnQoMCwgb3MucGF0aC5qb2luKG9zLnBhdGguZGlybmFtZShfX2ZpbGVfXyksICIuLiIpKQpHRUNJQ0kgPSB0ZW1wZmlsZS5ta2R0
ZW1wKCkKb3MuZW52aXJvbi5zZXRkZWZhdWx0KCJEQVRBX0RJUiIsIEdFQ0lDSSkKZnJvbSBrdXR1cGhhbmUgaW1wb3J0IGtheW5h
ayBhcyBTLCByYXBvciBhcyBSCgprYWxhbiA9IFtdCgoKZGVmIGRlbmUoYWQsIGtvc3VsKToKICAgIHByaW50KCgiR0VDVEkgIiBp
ZiBrb3N1bCBlbHNlICJLQUxESSAiKSArIGFkKQogICAgaWYgbm90IGtvc3VsOgogICAgICAgIGthbGFuLmFwcGVuZChhZCkKCgoj
IDEpIGthecSxdDogZmFyayB2ZSBzaWxpbmRpClIuYmFzbGEoKQpSLmZhcmsoIkJ1IFx1ZTAwMjEyXHVlMDAzIHNleSBjb2sgZ8O8
emVsIGJpciBraXRhcC4iLCAiQnUgXHVlMDAyMTJcdWUwMDMgxZ9leSDDp29rIGfDvHplbCBiaXIga2l0YXAuIikKUi5mYXJrKCJI
acOnIGRlxJ9pxZ9tZXllbiBwYXJhZ3JhZi4iLCAiSGnDpyBkZcSfacWfbWV5ZW4gcGFyYWdyYWYuIikKUi5mYXJrKCJOYXPEsXIg
4oCZIMSxbiBldmkiLCAiTmFzxLFy4oCZxLFuIGV2aSIpICAgIyB5YWxuxLF6IGJvxZ9sdWsvbm9rdGFsYW1hClIuc2lsaW5kaSgi
w7xzdC9hbHQgYmlsZ2kgc2F0xLFyxLEiLCAiQWxlbWxlcmluIFPEsXJyxLEiKQpSLnNpbGluZGkoIsO8c3QvYWx0IGJpbGdpIHNh
dMSxcsSxIiwgIkFsZW1sZXJpbiBTxLFycsSxIikKa2l0ID0geyJrdW55ZSI6IHsiYmFzbGlrIjogeyJ0ciI6ICJEZW5lbWUifSwg
InlhemFyIjogeyJ0ciI6ICJZYXphciJ9LCAiYXNpbF9kaWwiOiAidHIiLCAia2F5bmFrIjogeyJhZCI6ICJkLnBkZiJ9LAogICAg
ICAgICAgICAgICAgICJjaWthcm1hIjogeyJvbmFyaW0iOiB7ImhhcmYiOiBUcnVlfX19LAogICAgICAgImJsb2tsYXIiOiBbeyJ0
dXIiOiAiYmFzbGlrIiwgInNldml5ZSI6IDEsICJtZXRpbiI6IHsidHIiOiAiR8SwUsSwxZ4ifSwgInNheWZhbGFyIjogW3sibm8i
OiAiNSJ9XX1dCiAgICAgICArIFt7InR1ciI6ICJiYXNsaWsiLCAic2V2aXllIjogMiwgIm1ldGluIjogeyJ0ciI6IGYie259LiBL
VURTxLAgSEFExLBTIn19IGZvciBuIGluICgxLCAyLCAzLCA1LCA2KV0KICAgICAgICsgW3sidHVyIjogInAiLCAibWV0aW4iOiB7
InRyIjogIlnDvGNlIEFsbGFoIMWfw7Z5bGUgYnV5dXJtYWt0YWTEsXIge3tuMDAwMX19In0sICJzYXlmYWxhciI6IFt7Im5vIjog
IjYifSwgeyJubyI6ICI3In1dfSwKICAgICAgICAgIHsidHVyIjogInAiLCAibWV0aW4iOiB7InRyIjogIkthbGJpIHRlbWl6IG9s
bWF5YW5hIMWfYcWfYXLEsW0ge3tuMDAwMn19In0sICJzYXlmYWxhciI6IFt7Im5vIjogIjkifV19LAogICAgICAgICAgeyJ0dXIi
OiAicCIsICJtZXRpbiI6IHsidHIiOiAiUnVkc3QgYWdnZ2xlIG1hbSBTYXphbGkifX0sCiAgICAgICAgICB7InR1ciI6ICJwIiwg
Im1ldGluIjogeyJ0ciI6ICIxMiBCdWjDonLDriwgVGV2aMOuZCwgMzU7IE3DvHNsaW0sIMSwbcOibiwgMzEyLiJ9fV0sCiAgICAg
ICAiZGlwbm90bGFyIjogeyJuMDAwMSI6IHsibWV0aW4iOiB7InRyIjogIkJrLiBCdWjDonLDriwgVGV2aMOuZCwgMzUuIn19fX0K
ciA9IFIuYml0aXIoa2l0LCB7InNheWZhIjogMTAsICJvY3IiOiAyfSwgIi5wZGYiKQpkZyA9IHsoZFsib25jZSJdLCBkWyJzb25y
YSJdKTogZCBmb3IgZCBpbiByWyJkZWdpc2lrbGlrIl19CmRlbmUoIktlbGltZSBkZcSfacWfaWtsacSfaSBrYXlkZWRpbGlyIChz
ZXkgLT4gxZ9leSwgY29rIC0+IMOnb2spIiwgKCJzZXkgY29rIiwgIsWfZXkgw6dvayIpIGluIGRnKQpkZW5lKCJEZcSfacWfaWts
acSfaW4gc2F5ZmFzxLEgYmlsaW5pciIsIGRnLmdldCgoInNleSBjb2siLCAixZ9leSDDp29rIiksIHt9KS5nZXQoInNheWZhIikg
PT0gIjEyIikKZGVuZSgiWWFsbsSxeiBib8WfbHVrL25va3RhbGFtYSBheXLEsSBzYXnEsWzEsXIiLCByWyJkZWdpc2lrbGlrX3Rv
cGxhbSJdWyJub2t0YWxhbWFfYm9zbHVrIl0gPT0gMSBhbmQgbGVuKGRnKSA9PSAxKQpkZW5lKCJTaWxpbmVuIMO8c3QgYmlsZ2kg
c2F5xLFsxLFyIiwgclsic2lsaW5lbiJdWyLDvHN0L2FsdCBiaWxnaSBzYXTEsXLEsSJdWzBdWyJhZGV0Il0gPT0gMikKcyA9IHJb
InlhcGkiXVsibnVtYXJhbGlfYmFzbGlrX3NvcnVubGFyaSJdCmRlbmUoIk51bWFyYWzEsSBiYcWfbMSxa3RhIGVrc2lrIGJ1bHVu
dXIgKDQpIiwgcyBhbmQgc1swXVsiZWtzaWsiXSA9PSBbNF0pCmRlbmUoIlNheWZhIGF0bGFtYXPEsSBidWx1bnVyICg3IC0+IDkp
IiwgWzcsIDldIGluIHJbInlhcGkiXVsic2F5ZmEiXVsiYXRsYW1hIl0pCmRlbmUoIk1ldG5pIG9sbWF5YW4gZGlwbm90IGnFn2Fy
ZXRpIGJ1bHVudXIiLCByWyJ5YXBpIl1bImRpcG5vdCJdWyJtZXRuaV9vbG1heWFuX2lzYXJldCJdID09IDEpCmRlbmUoIkRpcG5v
dGEgYmVuemV5ZW4gZ8O2dmRlIHBhcmFncmFmxLEgYnVsdW51ciIsIGFueSgiQnVow6Jyw64iIGluIHQgZm9yIHQgaW4gclsieWFw
aSJdWyJkaXBub3RhX2JlbnpleWVuX3BhcmFncmFmIl0pKQpkZW5lKCLDh8O2cCBzYXTEsXIgxZ/DvHBoZWxpIHBhcmFncmFmIiwg
YW55KCJSdWRzdCIgaW4gcFsibWV0aW4iXSBmb3IgcCBpbiByWyJzdXBoZWxpX3BhcmFncmFmIl0pKQpkZW5lKCLFnsO8cGhlbGkg
a2VsaW1lIGxpc3Rlc2luZGUgJ2FnZ2dsZSciLCBhbnkoZFsia2VsaW1lIl0gPT0gImFnZ2dsZSIgZm9yIGQgaW4gclsic3VwaGVs
aV9rZWxpbWUiXSkpCmRlbmUoIkRvxJ9ydSBrZWxpbWUgxZ/DvHBoZWxpIHNhecSxbG1heiAoJ2thbGJpJywgJ3RlbWl6JykiLCBu
b3QgYW55KGRbImtlbGltZSJdIGluICgia2FsYmkiLCAidGVtaXoiKSBmb3IgZCBpbiByWyJzdXBoZWxpX2tlbGltZSJdKSkKa2wg
PSBvcy5wYXRoLmpvaW4oR0VDSUNJLCAia2l0YXBsYXIiLCAiZGVuZW1lLWFiYzEyMyIpClIua2F5ZGV0KGtsLCByKQpkZW5lKCJy
YXBvci5qc29uIHZlIHJhcG9yLnR4dCB5YXrEsWzEsXIiLCBvcy5wYXRoLmV4aXN0cyhvcy5wYXRoLmpvaW4oa2wsICJyYXBvci5q
c29uIikpIGFuZCAiTlVNQVJBTEkgQkHFnkxJSyIgaW4gb3Blbihvcy5wYXRoLmpvaW4oa2wsICJyYXBvci50eHQiKSwgZW5jb2Rp
bmc9InV0Zi04IikucmVhZCgpKQp0ID0gUi50b3BsdShvcy5wYXRoLmpvaW4oR0VDSUNJLCAia2l0YXBsYXIiKSkKZGVuZSgiVG9w
bHUgcmFwb3Iga2l0YWLEsSBpw6dlcmlyIiwgIltkZW5lbWUtYWJjMTIzXSIgaW4gdCBhbmQgIkRFRFBMQVkgVE9QTFUgUkFQT1Ig
4oCUIDEga2l0YXAiIGluIHQpCgojIDIpIGdlcsOnZWsgYWvEscWfOiBtZXRpbiBkb3N5YXPEsSAtPiBraXRhcDsgcmFwb3Igb2x1
xZ91ciwgbWV0aW4gYXluxLEga2FsxLFyCnlvbCA9IG9zLnBhdGguam9pbihHRUNJQ0ksICJEZW5lbWUgS2l0YWLEsSAtIFlhemFy
LnR4dCIpCndpdGggb3Blbih5b2wsICJ3IiwgZW5jb2Rpbmc9InV0Zi04IikgYXMgZjoKICAgIGYud3JpdGUoIkLEsFLEsE5DxLAg
QsOWTMOcTVxuXG5CdSBraXRhcCB0YW1hbWVuIGRvxJ9ydSB5YXrEsWxtxLHFnyBiaXIgbWV0aW5kaXIuIEhlciBrZWxpbWVzaSB5
ZXJpbmRlZGlyLlxuXG4iCiAgICAgICAgICAgICLEsGtpbmNpIHBhcmFncmFmIGRhIGhhdGFzxLF6ZMSxcjsgbcO8dHRha2kga2lt
c2VsZXIsIGJhaHMgZWRpbGVuIGtvbnVsYXIgdmUgw6JoaXJldCBrb3J1bm1hbMSxZMSxci5cbiIpCmtpdDIgPSBTLmNldmlyKHlv
bCwgTm9uZSwgeyJ5b2wiOiB5b2x9KQpyMiA9IFIuYWwoKQpkZW5lKCJNZXRpbiBrYXluYcSfxLFuZGEgcmFwb3Igb2x1xZ91ciIs
IHIyIGFuZCByMi5nZXQoImtpdGFwIiwge30pLmdldCgidHVyIikgPT0gInR4dCIpCmRlbmUoIkhhdGFzxLF6IG1ldGluZGUgZGXE
n2nFn2lrbGlrIHlvayIsIHIyIGFuZCByMlsiZGVnaXNpa2xpa190b3BsYW0iXVsiZmFya2xpIl0gPT0gMCkKbWV0aW4gPSAiICIu
am9pbihiWyJtZXRpbiJdWyJ0ciJdIGZvciBiIGluIGtpdDJbImJsb2tsYXIiXSkKZGVuZSgiTWV0aW4ga29ydW51ciAobcO8dHRh
a2ksIGJhaHMsIMOiaGlyZXQpIiwgYWxsKGsgaW4gbWV0aW4gZm9yIGsgaW4gKCJtw7x0dGFraSIsICJiYWhzIiwgIsOiaGlyZXQi
KSkpCgojIDMpIHJhcG9yIGhhdGEgdmVyc2UgZGUga2l0YXAgacWfbGVuaXIKZXNraSA9IFIub2x1c3R1cgpSLm9sdXN0dXIgPSBs
YW1iZGEgKmEsICoqazogMSAvIDAKa2l0MyA9IFMuY2V2aXIoeW9sLCBOb25lLCB7InlvbCI6IHlvbH0pCnIzID0gUi5hbCgpClIu
b2x1c3R1ciA9IGVza2kKZGVuZSgiUmFwb3IgaGF0YXPEsSBraXRhYsSxIGR1cmR1cm1heiIsIGtpdDMgYW5kIHIzIGFuZCAiWmVy
b0RpdmlzaW9uRXJyb3IiIGluIHIzLmdldCgiaGF0YSIsICIiKSkKZGVuZSgiUmFwb3IgaGF0YXPEsSBtZXRuaSBkZcSfacWfdGly
bWV6IiwgIiAiLmpvaW4oYlsibWV0aW4iXVsidHIiXSBmb3IgYiBpbiBraXQzWyJibG9rbGFyIl0pID09IG1ldGluKQoKcHJpbnQo
IlNPTlVDOiBIRVBTSSBHRUNUSSIgaWYgbm90IGthbGFuIGVsc2UgZiJTT05VQzoge2xlbihrYWxhbil9IFRFU1QgS0FMREkiKQo=
""",
}
for yol, veri in YENI.items():
    icerik = base64.b64decode("".join(veri.split()))
    p = pathlib.Path(yol)
    if p.exists() and p.read_bytes() == icerik:
        print("ATLANDI: " + yol)
    else:
        p.write_bytes(icerik)
        print("TAMAM: " + yol + " (" + hashlib.md5(icerik).hexdigest() + ")")


def degistir(s, eski, yeni, ad, adet=1):
    if s.count(eski) != adet:
        sys.exit(f"HATA: {ad}: beklenen metin {adet} kez bulunamadı ({s.count(eski)})")
    return s.replace(eski, yeni)


p = pathlib.Path("kutuphane/kaynak.py")
s = p.read_text(encoding="utf-8")
if "from . import rapor as R" in s:
    print("ATLANDI: kaynak.py zaten yamalı")
else:
    s = degistir(s, "from . import kitap as K\n", "from . import kitap as K\nfrom . import rapor as R  # 0.5.23: kitap raporu (yalnız kayıt)\n", "içe aktarma")
    # üst/alt bilgi olarak silinen satırlar
    s = degistir(s, """        out.append([r for r in rows if not (id(r) in ilk_son and anahtar(r["text"]) in tekrar)])
    return out
""", """        kalan = [r for r in rows if not (id(r) in ilk_son and anahtar(r["text"]) in tekrar)]
        for r in rows:
            if id(r) in ilk_son and anahtar(r["text"]) in tekrar:
                R.silindi("üst/alt bilgi satırı", r["text"])
        out.append(kalan)
    return out
""", "tekrar edenler")
    # atılan ön/son sayfalar ve içindekiler sayfaları
    s = degistir(s, """    satirlar_k = _tekrar_edenleri_at([satirlar[i] for i in kalan])
""", """    for i in sorted(set(range(n)) - set(kalan)):
        ilk = " / ".join(r["text"] for r in satirlar[i][:3])
        if ilk.strip():
            R.silindi("içindekiler sayfası" if i in (toc_sayfalari or []) else "atılan ön/son sayfa", f"PDF s.{i + 1}: {ilk}")
    satirlar_k = _tekrar_edenleri_at([satirlar[i] for i in kalan])
""", "atılan sayfalar")
    # _duzelt: paragraf başına önce/sonra
    s = degistir(s, """def _duzelt(metinler, onar=None):""", """def _duzelt(metinler, onar=None, yer="metin"):""", "_duzelt imzası")
    s = degistir(s, """    for p in metinler:
        p = DZ.satir_ici_ust_bilgileri_sil(p, basliklar)""", """    for p in metinler:
        p0 = p
        p = DZ.satir_ici_ust_bilgileri_sil(p, basliklar)""", "_duzelt başı")
    s = degistir(s, """        p = re.sub(r"^(\\d{1,3}[.)])(?=[^\\s\\d.)\\ue002])", r"\\1 ", p)
        out.append(p)
    return out
""", """        p = re.sub(r"^(\\d{1,3}[.)])(?=[^\\s\\d.)\\ue002])", r"\\1 ", p)
        R.fark(p0, p, yer)
        out.append(p)
    return out
""", "_duzelt sonu")
    s = degistir(s, """    notlar = dict(zip(notlar, _duzelt(list(notlar.values()), onar))) if notlar else {}""",
                 """    notlar = dict(zip(notlar, _duzelt(list(notlar.values()), onar, "dipnot"))) if notlar else {}""", "dipnot düzelt")
    # forma işareti
    s = degistir(s, """                m = forma.sub("", o["metin"])
                if m != o["metin"]:""", """                m = forma.sub("", o["metin"])
                R.fark(o["metin"], m, "forma işareti")
                if m != o["metin"]:""", "forma")
    # çöp paragraf
    s = degistir(s, """            tasinan += [e for e, _ in sayfalar]
            continue""", """            tasinan += [e for e, _ in sayfalar]
            R.silindi("çöp paragraf", yazi or temiz)
            continue""", "çöp paragraf")
    # başlık onarımı
    s = degistir(s, """            if len(temiz2) == len(temiz):  # uzunluk aynı kalır (harf değişimi): sayfa konumları geçerli
                temiz = temiz2""", """            if len(temiz2) == len(temiz):  # uzunluk aynı kalır (harf değişimi): sayfa konumları geçerli
                R.fark(temiz, temiz2, "başlık")
                temiz = temiz2""", "başlık onarımı")
    # bağlanamayan dipnot
    s = degistir(s, """    kit["dipnotlar"] = {g: {"metin": {"tr": t}} for g, t in notlar.items() if g in kullanilan}""",
                 """    kit["dipnotlar"] = {g: {"metin": {"tr": t}} for g, t in notlar.items() if g in kullanilan}
    for g, t in notlar.items():
        if g not in kullanilan:
            R.silindi("bağlanamayan dipnot", t)""", "yetim dipnot")
    # cevir: kayıt başla/bitir
    s = degistir(s, """    ogeler, notlar, bilgi = okuyucu(yol, ilerleme)
    if ilerleme:
        ilerleme("Metin düzeltiliyor")""", """    R.basla()
    ogeler, notlar, bilgi = okuyucu(yol, ilerleme)
    if ilerleme:
        ilerleme("Metin düzeltiliyor")""", "cevir başı")
    s = degistir(s, """    if not any(b["tur"] == "p" for b in kit["bloklar"]):
        raise ValueError("Dosyadan metin çıkarılamadı (boş ya da okunamayan dosya)")
    return kit
""", """    if not any(b["tur"] == "p" for b in kit["bloklar"]):
        raise ValueError("Dosyadan metin çıkarılamadı (boş ya da okunamayan dosya)")
    R.bitir(kit, bilgi, uzanti)
    return kit
""", "cevir sonu")
    p.write_text(s, encoding="utf-8")
    print("TAMAM: kaynak.py")

p = pathlib.Path("kutuphane/depo.py")
s = p.read_text(encoding="utf-8")
if "rapor.kaydet" in s:
    print("ATLANDI: depo.py zaten yamalı")
else:
    s = degistir(s, """    kit = kaynak.cevir(yol, lambda m: durum_asama(kid, m), {"yol": yol}, kapak_yolu=os.path.join(klasor(kid), "kapak"))
""", """    kit = kaynak.cevir(yol, lambda m: durum_asama(kid, m), {"yol": yol}, kapak_yolu=os.path.join(klasor(kid), "kapak"))
    try:  # 0.5.23: kitap raporu (rapor.json, rapor.txt); hata kitabı durdurmaz
        from . import rapor
        rapor.kaydet(klasor(kid), rapor.al())
    except Exception:
        pass
""", "depo rapor")
    p.write_text(s, encoding="utf-8")
    print("TAMAM: depo.py")

p = pathlib.Path("kutuphane/main.py")
s = p.read_text(encoding="utf-8")
if "/api/rapor" in s:
    print("ATLANDI: main.py zaten yamalı")
else:
    s = degistir(s, 'SURUM = "0.5.22"', 'SURUM = "0.5.23"', "SURUM")
    s = degistir(s, """@app.get("/api/kitaplar")
""", """@app.get("/api/rapor")
def toplu_rapor(uzun: int = 0):
    \"\"\"0.5.23: bütün kitapların raporlarının özeti (düz metin; tarayıcıda açılıp kaydedilebilir).\"\"\"
    from . import rapor
    return Response(rapor.toplu(kisa=not uzun), media_type="text/plain; charset=utf-8")


@app.get("/api/kitaplar/{kid}/rapor")
def kitap_raporu(kid: str):
    yol = os.path.join(depo.klasor(kid), "rapor.txt")
    if not os.path.exists(yol):
        raise HTTPException(404, "Bu kitabın raporu yok (0.5.23'ten önce işlenmiş; yeniden yüklenince oluşur)")
    return Response(open(yol, encoding="utf-8").read(), media_type="text/plain; charset=utf-8")


@app.get("/api/kitaplar")
""", "main adresler")
    p.write_text(s, encoding="utf-8")
    print("TAMAM: main.py")
